@date = 2026-03-09
@stockId=9999

# 一次只允許查一天的一支股票
GET {{$dotenv Domain}}/data?dataset=TaiwanStockKBar&start_date={{date}}&data_id={{stockId}}
Authorization: Bearer {{$processEnv Finmind__Token}}


# {
#   "msg": "success",
#   "status": 200,
#   "data": [
#     {
#       "date": "2026-03-09",
#       "minute": "09:00:00",
#       "stock_id": "2330",
#       "open": 1775.0,
#       "high": 1780.0,
#       "low": 1770.0,
#       "close": 1775.0,
#       "volume": 9189
#     },
#     {
#       "date": "2026-03-09",
#       "minute": "09:01:00",
#       "stock_id": "2330",
#       "open": 1780.0,
#       "high": 1780.0,
#       "low": 1775.0,
#       "close": 1780.0,
#       "volume": 1432
#     }
#   ]
# }
