@stockId = 2603
@date1 = 2026-05-01
@date2=2026-12-31

# 所有個股日成交資訊
GET {{$dotenv Domain}}/data?dataset=TaiwanStockTradingDate&start_date={{date1}}&end_date={{date2}}


# {
#   "msg": "success",
#   "status": 200,
#   "data": [
#     {
#       "date": "2026-05-04"
#     },
#     {
#       "date": "2026-05-05"
#     },
#     {
#       "date": "2026-05-06"
#     },
#     {
#       "date": "2026-05-07"
#     },
#     {
#       "date": "2026-05-08"
#     },
#     {
#       "date": "2026-05-11"
#     },
#     {
#       "date": "2026-05-12"
#     },
#     {
#       "date": "2026-05-13"
#     },
#     {
#       "date": "2026-05-14"
#     }
#   ]
# }