// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewStock.EFModels;

#nullable disable

namespace NewStock.EFModels.Migrations
{
    [DbContext(typeof(NewStockContext))]
    [Migration("20260515185102_update周月K資料表")]
    partial class update周月K資料表
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NewStock.EFModels.StockDayInfo", b =>
                {
                    b.Property<short>("StockId")
                        .HasColumnType("smallint");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<double>("平盤價")
                        .HasColumnType("float");

                    b.Property<long>("成交量")
                        .HasColumnType("bigint");

                    b.Property<double>("收盤價")
                        .HasColumnType("float");

                    b.Property<double>("最低價")
                        .HasColumnType("float");

                    b.Property<double>("最高價")
                        .HasColumnType("float");

                    b.Property<double>("漲幅")
                        .HasColumnType("float");

                    b.Property<double>("開盤價")
                        .HasColumnType("float");

                    b.HasKey("StockId", "Date");

                    b.ToTable("StockDayInfo");
                });

            modelBuilder.Entity("NewStock.EFModels.StockInfo", b =>
                {
                    b.Property<short>("StockId")
                        .HasColumnType("smallint");

                    b.Property<string>("IndustryCategory")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("MarketType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("StockName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("StockId");

                    b.ToTable("StockInfo");
                });

            modelBuilder.Entity("NewStock.EFModels.TaiwanTradingDay", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.HasKey("Date");

                    b.ToTable("TaiwanTradingDay");
                });

            modelBuilder.Entity("NewStock.EFModels.周月K資料表", b =>
                {
                    b.Property<short>("StockId")
                        .HasColumnType("smallint");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("TimeType")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long>("交易筆數")
                        .HasColumnType("bigint");

                    b.Property<double>("平盤價")
                        .HasColumnType("float");

                    b.Property<double>("收盤價")
                        .HasColumnType("float");

                    b.Property<double>("最低價")
                        .HasColumnType("float");

                    b.Property<double>("最高價")
                        .HasColumnType("float");

                    b.Property<double>("漲幅")
                        .HasColumnType("float");

                    b.Property<double>("開盤價")
                        .HasColumnType("float");

                    b.HasKey("StockId", "Date", "TimeType");

                    b.ToTable("周月K資料表");
                });

            modelBuilder.Entity("NewStock.EFModels.StockDayInfo", b =>
                {
                    b.HasOne("NewStock.EFModels.StockInfo", "Stock")
                        .WithMany("StockDayInfos")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("NewStock.EFModels.周月K資料表", b =>
                {
                    b.HasOne("NewStock.EFModels.StockInfo", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("NewStock.EFModels.StockInfo", b =>
                {
                    b.Navigation("StockDayInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
