@stockId = 2603
@date = 2026-05-11

# 單一個股日成交資訊
GET {{$dotenv Domain}}/data?dataset=TaiwanStockPrice&data_id={{stockId}}&start_date={{date}}&end_date={{date}}

# {
#   "msg": "success",
#   "status": 200,
#   "data": [
#     {
#       "date": "2026-05-11",
#       "stock_id": "2603",
#       "Trading_Volume": 9248306,
#       "Trading_money": 1979610125,
#       "open": 213.5,
#       "max": 215.0,
#       "min": 212.5,
#       "close": 214.0,
#       "spread": 2.5,
#       "Trading_turnover": 7859
#     }
#   ]
# }

###

# 所有個股日成交資訊
GET {{$dotenv Domain}}/data?dataset=TaiwanStockPrice&start_date={{date}}&end_date={{date}}
Authorization: Bearer {{$processEnv Finmind__Token}}

# {
#   "msg": "success",
#   "status": 200,
#   "data": [
#     {
#       "date": "2026-05-11",
#       "stock_id": "2603",
#       "Trading_Volume": 9248306,
#       "Trading_money": 1979610125,
#       "open": 213.5,
#       "max": 215.0,
#       "min": 212.5,
#       "close": 214.0,
#       "spread": 2.5,
#       "Trading_turnover": 7859
#     }
#   ]
# }
